- name: vars from a file
  hosts: localhost
  vars_prompt:
  - uname: USERNAME # entered username is stored in this variable
    prompt: Please enter your username 
    private: false
  - pswd: PASSWORD # entered password is stored in this variable
    prompt: Please enter your password
    private: true  # not visible when user is entering(for protection)
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, Username: {{USERNAME}}. Password is: {{PASSWORD}}"