- name: vars from inventory file
  hosts: localhost   # in sync with inventory file
  tasks:
  - name: print variables from inventory file
    ansible.builtin.debug:
      msg: "this message should find person with name {{name}} and {{surname}} as surname in {{city}} city"  